### ISSUE TITLE
The Fields is showing and then hidden

### ISSUE THREAD

**Issue by issour** [izi-dev/nova-conditional-if#2]
Hi,
Thank you for this package !!
In form create fields with condition is showing and one second later is hidden.
They are a way to do not show them when the form load until the condition is true.
Many thx

**Comment by izi-dev** [comment]
@issour Hi, 

Hello, if I agree, I am resolved, you can update to version 1.0.3, thanks.

https://github.com/izi-dev/nova-conditional-if/commit/430dd0ac0cf48bbd678cd231519cef4fcdcd7e62
