### ISSUE TITLE
Conditional in front

### ISSUE THREAD

**Issue by izi-dev** [izi-dev/nova-conditional-if#3]
I think "DependsOnContain" and "DependsOnNotContain" would be very useful and are easy to translate to JS (or add the ability to use regular expressions in DependsOn). I tried @izi-dev 's package and that works for my need but I use it on a text field (we need to show a password field only if the email field doesn't contain a certain domain) and that generates way too many API calls for my liking. Unfortunately I can't find another one that supports a "contains" type of condition.

_Originally posted by @uandco in https://github.com/epartment/nova-dependency-container/issues/118#issuecomment-659829175_

**Comment by izi-dev** [comment]
@uandco  
pls review,

https://github.com/izi-dev/nova-conditional-if/blame/master/README.md#L39

**Comment by uandco** [comment]
Thanks, that looks good, but you should indicate you have to select either a front end or back end check.
For the front end one, in your example, `_value.name` should be `type.value`, following the back end example.

**Comment by izi-dev** [comment]
> Thanks, that looks good, but you should indicate you have to select either a front end or back end check.
> For the front end one, in your example, `_value.name` should be `type.value`, following the back end example.

hahaha, my mistake, I already solve it
