### ISSUE TITLE
Doesn't work with belongs to fields.

### ISSUE THREAD

**Issue by uandco** [izi-dev/nova-conditional-if#7]
`getValueComponentDependency(attribute)`

returns

`'value': component.value`

and doesn't use this method, which is supposed to return the actual value:

`findWatchableComponentAttribute`

As a result, the validation method gets passed an undefined value as these components don't have a `value` property.

**Comment by uandco** [comment]
I tested with this:
```
return {
    'attribute': component.field.attribute,
    'value': component.value || component[this.findWatchableComponentAttribute(component)].value
};

```

It works but would only work for normal fields, belongs to and belongs to many, not for morph-to-field, also it's quite ugly ;-)

**Comment by izi-dev** [comment]
Might you help me? the truth is that I haven't worked on the project for a while.

**Comment by uandco** [comment]
Sure, I thought it would be best to have an additional method, similar to `findWatchableComponentAttribute`, that would return the value, but I'm not sure where the value is for `morph-to-field` components.

Something like `getComponentValue` that we can call here:

```
return {
    'attribute': component.field.attribute,
    'value': this.getComponentValue(component)
};
```

**Comment by uandco** [comment]
I created a PR for that, see https://github.com/izi-dev/nova-conditional-if/pull/10

**Comment by uandco** [comment]
@izi-dev have you had a chance to review that PR? Cheers

**Comment by izi-dev** [comment]
Sorry, I have been very busy with my work, but I am already catching up with the package, it seems like a good solution, thank you very much.

**Comment by uandco** [comment]
No worries and thanks for merging!
Any idea when you plan to release it? Thanks.

**Comment by izi-dev** [comment]
> ¿Alguna idea de cuándo planeas liberarlo? Gracias.

I will work on this
